import { effectiveNetBurn, formatUsd } from "./finance";
import type { RunwayState } from "../types/runway";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildInvestorUpdateHtml(
  state: RunwayState,
  runwayMonths: number | null,
  opts: { wins: string; asks: string }
): string {
  const nb = effectiveNetBurn(state.monthlyBurn, state.monthlyRevenue, state.monthlyDebtService);
  const runwayStr =
    runwayMonths === null ? "∞ (net burn ≤ 0)" : `${runwayMonths.toFixed(1)} months`;
  const monthYear = new Date().toLocaleString("en-US", { month: "long", year: "numeric" });

  const winsHtml = opts.wins.trim()
    ? `<ul>${opts.wins
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean)
        .map((l) => `<li>${escapeHtml(l)}</li>`)
        .join("")}</ul>`
    : "<p><em>No wins listed.</em></p>";

  const asksHtml = opts.asks.trim()
    ? `<ul>${opts.asks
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean)
        .map((l) => `<li>${escapeHtml(l)}</li>`)
        .join("")}</ul>`
    : "<p><em>No asks listed.</em></p>";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Investor update — ${escapeHtml(monthYear)}</title>
</head>
<body style="font-family:system-ui,-apple-system,sans-serif;line-height:1.5;color:#111;max-width:640px;margin:24px auto;padding:0 16px;">
  <h1 style="font-size:20px;margin-bottom:8px;">Investor update</h1>
  <p style="color:#555;font-size:14px;margin-top:0;">${escapeHtml(monthYear)} · Runway (prototype)</p>

  <h2 style="font-size:15px;margin-top:24px;">Financial snapshot (USD)</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">
    <tr><td style="padding:6px 0;border-bottom:1px solid #eee;">Cash on hand</td><td style="padding:6px 0;border-bottom:1px solid #eee;text-align:right;font-weight:600;">${formatUsd(state.cashOnHand)}</td></tr>
    <tr><td style="padding:6px 0;border-bottom:1px solid #eee;">Gross burn / mo</td><td style="padding:6px 0;border-bottom:1px solid #eee;text-align:right;">${formatUsd(state.monthlyBurn)}</td></tr>
    <tr><td style="padding:6px 0;border-bottom:1px solid #eee;">Revenue (MRR-style) / mo</td><td style="padding:6px 0;border-bottom:1px solid #eee;text-align:right;">${formatUsd(state.monthlyRevenue)}</td></tr>
    <tr><td style="padding:6px 0;border-bottom:1px solid #eee;">Net burn / mo</td><td style="padding:6px 0;border-bottom:1px solid #eee;text-align:right;">${formatUsd(nb)}</td></tr>
    <tr><td style="padding:6px 0;border-bottom:1px solid #eee;">Runway</td><td style="padding:6px 0;border-bottom:1px solid #eee;text-align:right;font-weight:600;">${escapeHtml(runwayStr)}</td></tr>
    <tr><td style="padding:6px 0;">Rev. MoM growth</td><td style="padding:6px 0;text-align:right;">${state.momGrowthPct >= 0 ? "+" : ""}${state.momGrowthPct.toFixed(1)}%</td></tr>
  </table>

  <h2 style="font-size:15px;margin-top:24px;">Wins</h2>
  ${winsHtml}

  <h2 style="font-size:15px;margin-top:24px;">Asks</h2>
  ${asksHtml}

  <p style="margin-top:32px;font-size:12px;color:#888;">Generated by Runway. Not financial advice.</p>
</body>
</html>`;
}
